var S=Object.create;var h=Object.defineProperty;var C=Object.getOwnPropertyDescriptor;var E=Object.getOwnPropertyNames;var j=Object.getPrototypeOf,L=Object.prototype.hasOwnProperty;var O=(e,n)=>{for(var l in n)h(e,l,{get:n[l],enumerable:!0})},f=(e,n,l,o)=>{if(n&&typeof n=="object"||typeof n=="function")for(let t of E(n))!L.call(e,t)&&t!==l&&h(e,t,{get:()=>n[t],enumerable:!(o=C(n,t))||o.enumerable});return e};var m=(e,n,l)=>(l=e!=null?S(j(e)):{},f(n||!e||!e.__esModule?h(l,"default",{value:e,enumerable:!0}):l,e)),b=e=>f(h({},"__esModule",{value:!0}),e);var P={};O(P,{Bundle:()=>x});module.exports=b(P);var i=m(require("path"),1);var c=m(require("fs"),1),x=function(e,n,l="."){let o=i.default.basename(e);if(!o)throw new Error("The main file is null!");let t=i.default.basename(n),r=i.default.resolve(l).replaceAll("\\","/"),s=[],a="",u="",y=[r],p=null,g="(none)",d={"C/C++":[".h",".hpp",".c",".cc",".cpp"]},v=Object.keys(d),I=Object.values(d);c.default.writeFileSync(t,""),w(o),c.default.appendFileSync(t,a)};function Z(e){try{content2=content+e,content=content2}catch(n){c.default.appendFileSync(outputFile,content),c.default.appendFileSync(outputFile,e),content=""}}function w(e){B(e);let n=e;if(e=T(e),lastFile=e,!includedFiles.includes(e)){if(includedFiles.push(e),lang){if(!langToExt[lang].includes(i.default.extname(e)))throw new Error("Multiple languages detected!")}else{let l=null;for(let o=0;o<extsByLang.length;o++)extsByLang[o].includes(i.default.extname(e))&&(l=o);if(l==null)throw new Error("Unsupported language detected!");lang=langs[l],console.log(`
Language:
`+lang)}Z("// File: "+n+`
`),lang=="C/C++"&&A(e)}}function B(e){console.log(`
Directories:
`+searchZone.join(`
`)),console.log(`
Processing:
`+e)}function F(){for(let e=0;e<searchZone.length;e++)for(let n=0;n<searchZone.length;n++)e!=n&&searchZone[e].includes(searchZone[n])&&(searchZone[n]="*");searchZone=searchZone.filter(e=>e!="*")}function T(e){F();for(let n=0;n<searchZone.length;n++){let l=searchZone[n],o=i.default.basename(e),t=i.default.dirname(i.default.resolve(e)).replaceAll("\\","/"),r=i.default.dirname(l),s=r.split("/"),a=t.split("/"),u=null;for(;u==null&&s.length>0;){let g=s[s.length-1],d=a.indexOf(g);d>-1?(s.pop(),u=d):s.pop()}u!=null&&(t=a.slice(u+1,a.length).join("/"));let p=[[r,t].join("/"),o].join("/").replaceAll("//","/");if(c.default.existsSync(p))return searchZone.push(i.default.dirname(p)),F(),p}throw new Error(e+" was not found! Caller: "+lastFile)}function A(e){let l=c.default.readFileSync(e,{encoding:"utf8"}).split(`
`);for(let o=0;o<l.length;o++){let t=l[o];if(t.includes('#include "')||t.includes("#include '")){let r=t.trim().replace(/#include ([\"\'])/,"").replace(/([\"\']).*$/,"");w(r)}else Z(t+`
`)}}0&&(module.exports={Bundle});
